### POST /transactions – create a new transaction
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "payerId": 1,
  "payeeId": 2,
  "value": 100.00
}

### GET /transactions – list all transactions (check notification flags)
GET http://localhost:8080/transactions


### POST /transactions – create a new transaction error insufficient funds
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "payerId": 1,
  "payeeId": 2,
  "value": 2000.00
}

### Post /transactions – create a new transaction user common pays merchant
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "payerId": 2,
  "payeeId": 3,
  "value": 250.00
}


### POST /transactions – create a new transaction error payer is merchant
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "payerId": 3,
  "payeeId": 2,
  "value": 100.00
}

### Post /transactions – create a new transaction error user not found
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "payerId": 99,
  "payeeId": 2,
  "value": 100.00
}